
server:
  port: 8009

##配置 Jpa
#jpa:
#  properties:
#    hibernate:
#      ddl-auto: none
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      enable_lazy_load_no_trans: true
#  open-in-view: true

#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stringboot_jpa?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      #     更新或者创建数据表结构
      ddl-auto: update
    #    控制台显示SQL
    show-sql: true