

server:
  port: 9007


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stringboot_jpa?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456


mybatis:
  typeAliasesPackage: com.qiao.springbootmybatis.entity
  mapperLocations: classpath:mapper/*.xml